// generated by build/make_presence_display.py, do not edit.
const PRESENCE_INDEX = [
 {
  "key": "steelhead",
  "label": "Steelhead",
  "colour": "#7a5c99",
  "lines": 32791,
  "polys": 0,
  "polys_merged": 0,
  "vertices": 393710,
  "vertices_ranges": 0,
  "vertices_merged": 0,
  "mb": 7.85,
  "parts_dropped_as_degenerate": 441,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "ca_cdfw_ds340_179",
    "label": "CA, CDFW ds340, Winter",
    "sources": [
     "CDFW BIOS ds340 Winter Steelhead Distribution, June 2012"
    ],
    "runs": [
     "Winter"
    ],
    "state": "CA",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 8899,
    "polys": 0,
    "polys_merged": 0
   },
   {
    "id": "ca_cdfw_ds341_025",
    "label": "CA, CDFW ds341, Summer",
    "sources": [
     "CDFW BIOS ds341 Summer Steelhead Distribution, October 2009"
    ],
    "runs": [
     "Summer"
    ],
    "state": "CA",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 763,
    "polys": 0,
    "polys_merged": 0
   },
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW, Winter + Summer",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_SteelheadSummer",
     "ODFW Fish Habitat Distribution 1167_5, fhd_SteelheadWinter"
    ],
    "runs": [
     "Winter",
     "Summer"
    ],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 15010,
    "polys": 0,
    "polys_merged": 0
   },
   {
    "id": "wa_swifd_097",
    "label": "WA, SWIFD, Summer + Winter",
    "sources": [
     "WDFW SWIFD, file geodatabase of 2026-04-17"
    ],
    "runs": [
     "Summer",
     "Winter"
    ],
    "state": "WA",
    "notes": [
     "2,155 of these reaches are presumed rather than recorded: the source marks them as likely habitat, not as a documented observation."
    ],
    "grade": "observed/presumed",
    "grain": "reach",
    "lines": 8119,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "coho",
  "label": "Coho salmon",
  "colour": "#b0663c",
  "lines": 23280,
  "polys": 0,
  "polys_merged": 0,
  "vertices": 216364,
  "vertices_ranges": 0,
  "vertices_merged": 0,
  "mb": 4.33,
  "parts_dropped_as_degenerate": 39,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "ca_cdfw_ds326_405",
    "label": "CA, CDFW ds326",
    "sources": [
     "CDFW BIOS ds326 Coho Distribution, August 2025"
    ],
    "runs": [],
    "state": "CA",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 776,
    "polys": 0,
    "polys_merged": 0
   },
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_Coho"
    ],
    "runs": [],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 12643,
    "polys": 0,
    "polys_merged": 0
   },
   {
    "id": "wa_swifd_097",
    "label": "WA, SWIFD, Fall",
    "sources": [
     "WDFW SWIFD, file geodatabase of 2026-04-17"
    ],
    "runs": [
     "Fall"
    ],
    "state": "WA",
    "notes": [
     "1,704 of these reaches are presumed rather than recorded: the source marks them as likely habitat, not as a documented observation."
    ],
    "grade": "observed/presumed",
    "grain": "reach",
    "lines": 9861,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "chinook",
  "label": "Chinook salmon",
  "colour": "#3f8f7a",
  "lines": 9403,
  "polys": 766,
  "polys_merged": 42,
  "vertices": 308639,
  "vertices_ranges": 138012,
  "vertices_merged": 21311,
  "mb": 3.82,
  "parts_dropped_as_degenerate": 0,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "ca_noaa_ds981_027",
    "label": "CA, NOAA ds981, California Coastal",
    "sources": [
     "NOAA ds981 California Coastal Chinook distribution, 2005"
    ],
    "runs": [
     "California Coastal"
    ],
    "state": "CA",
    "notes": [
     "38 of these reaches are presumed rather than recorded: the source marks them as likely habitat, not as a documented observation."
    ],
    "grade": "observed/presumed",
    "grain": "reach",
    "lines": 300,
    "polys": 0,
    "polys_merged": 0
   },
   {
    "id": "ca_noaa_ds982_945",
    "label": "CA, NOAA ds982, Central Valley spring",
    "sources": [
     "NOAA ds982 Central Valley spring-run Chinook distribution, 2005"
    ],
    "runs": [
     "Central Valley spring"
    ],
    "state": "CA",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 161,
    "polys": 0,
    "polys_merged": 0
   },
   {
    "id": "ca_pisces_central_valley_591",
    "label": "CA, PISCES, Central Valley",
    "sources": [
     "PISCES 2.0.4 extant range, Oncorhynchus_tshawytscha_SOT05",
     "PISCES 2.0.4 extant range, Oncorhynchus_tshawytscha_SOT07",
     "PISCES 2.0.4 extant range, Oncorhynchus_tshawytscha_SOT08"
    ],
    "runs": [
     "Central Valley winter",
     "Central Valley late fall",
     "Central Valley fall"
    ],
    "state": "CA",
    "notes": [
     "Not a stream. PISCES maps fish onto whole HUC12 watersheds, a median of about 3 km across, so the shape says the fish is somewhere in this watershed, not that it is in any particular channel. Every California species is mapped this way; Oregon and Washington are mapped onto stream arcs instead. The change of shape at the state line is a change of institution, not of fish."
    ],
    "grade": "range",
    "grain": "HUC12 range",
    "lines": 0,
    "polys": 376,
    "polys_merged": 37
   },
   {
    "id": "ca_pisces_soncc_326",
    "label": "CA, PISCES, SONCC",
    "sources": [
     "PISCES 2.0.4 extant range, Oncorhynchus_tshawytscha_SOT03"
    ],
    "runs": [
     "SONCC fall"
    ],
    "state": "CA",
    "notes": [
     "Not a stream. PISCES maps fish onto whole HUC12 watersheds, a median of about 3 km across, so the shape says the fish is somewhere in this watershed, not that it is in any particular channel. Every California species is mapped this way; Oregon and Washington are mapped onto stream arcs instead. The change of shape at the state line is a change of institution, not of fish."
    ],
    "grade": "range",
    "grain": "HUC12 range",
    "lines": 0,
    "polys": 41,
    "polys_merged": 1
   },
   {
    "id": "ca_pisces_upper_klamath_trinity_010",
    "label": "CA, PISCES, Upper Klamath-Trinity",
    "sources": [
     "PISCES 2.0.4 extant range, Oncorhynchus_tshawytscha_SOT01",
     "PISCES 2.0.4 extant range, Oncorhynchus_tshawytscha_SOT02"
    ],
    "runs": [
     "Upper Klamath-Trinity fall",
     "Upper Klamath-Trinity spring"
    ],
    "state": "CA",
    "notes": [
     "Not a stream. PISCES maps fish onto whole HUC12 watersheds, a median of about 3 km across, so the shape says the fish is somewhere in this watershed, not that it is in any particular channel. Every California species is mapped this way; Oregon and Washington are mapped onto stream arcs instead. The change of shape at the state line is a change of institution, not of fish."
    ],
    "grade": "range",
    "grain": "HUC12 range",
    "lines": 0,
    "polys": 349,
    "polys_merged": 4
   },
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW, Fall + Spring",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_ChinookFall",
     "ODFW Fish Habitat Distribution 1167_5, fhd_ChinookSpring"
    ],
    "runs": [
     "Fall",
     "Spring"
    ],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 4981,
    "polys": 0,
    "polys_merged": 0
   },
   {
    "id": "wa_swifd_097",
    "label": "WA, SWIFD, Fall + Spring + Summer",
    "sources": [
     "WDFW SWIFD, file geodatabase of 2026-04-17"
    ],
    "runs": [
     "Fall",
     "Spring",
     "Summer"
    ],
    "state": "WA",
    "notes": [
     "552 of these reaches are presumed rather than recorded: the source marks them as likely habitat, not as a documented observation."
    ],
    "grade": "observed/presumed",
    "grain": "reach",
    "lines": 3961,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "coastal_cutthroat",
  "label": "Coastal cutthroat trout",
  "colour": "#c2447a",
  "lines": 51595,
  "polys": 85,
  "polys_merged": 3,
  "vertices": 372504,
  "vertices_ranges": 13306,
  "vertices_merged": 1861,
  "mb": 7.25,
  "parts_dropped_as_degenerate": 621,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "ca_pisces_957",
    "label": "CA, PISCES",
    "sources": [
     "PISCES 2.0.4 extant range, Oncorhynchus_clarki_clarki_SOC01"
    ],
    "runs": [],
    "state": "CA",
    "notes": [
     "Not a stream. PISCES maps fish onto whole HUC12 watersheds, a median of about 3 km across, so the shape says the fish is somewhere in this watershed, not that it is in any particular channel. Every California species is mapped this way; Oregon and Washington are mapped onto stream arcs instead. The change of shape at the state line is a change of institution, not of fish."
    ],
    "grade": "range",
    "grain": "HUC12 range",
    "lines": 0,
    "polys": 85,
    "polys_merged": 3
   },
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_Cutthroat_Coastal"
    ],
    "runs": [],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 45296,
    "polys": 0,
    "polys_merged": 0
   },
   {
    "id": "wa_swifd_097",
    "label": "WA, SWIFD",
    "sources": [
     "WDFW SWIFD, file geodatabase of 2026-04-17"
    ],
    "runs": [],
    "state": "WA",
    "notes": [
     "1,685 of these reaches are presumed rather than recorded: the source marks them as likely habitat, not as a documented observation."
    ],
    "grade": "observed/presumed",
    "grain": "reach",
    "lines": 6299,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "pacific_lamprey",
  "label": "Pacific lamprey",
  "colour": "#5a7fbf",
  "lines": 11040,
  "polys": 0,
  "polys_merged": 0,
  "vertices": 150824,
  "vertices_ranges": 0,
  "vertices_merged": 0,
  "mb": 3.01,
  "parts_dropped_as_degenerate": 13,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_Lamprey_Pacific"
    ],
    "runs": [],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 2106,
    "polys": 0,
    "polys_merged": 0
   },
   {
    "id": "us_usfws_2022_235",
    "label": "US, USFWS 2022",
    "sources": [
     "USFWS Pacific Lamprey Known Observations And Distribution 2022, layer 45"
    ],
    "runs": [],
    "state": "US",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 2448,
    "polys": 0,
    "polys_merged": 0
   },
   {
    "id": "us_usfws_ds2673_396",
    "label": "US, USFWS ds2673",
    "sources": [
     "USFWS ds2673 Pacific lamprey current distribution, 2021"
    ],
    "runs": [],
    "state": "US",
    "notes": [
     "These lines are derived by USFWS from NHDPlusV2, fourth-order streams and above, rather than traced from observations. The derivation is the agency's, not this project's."
    ],
    "grade": "observed",
    "grain": "reach",
    "lines": 6486,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "redband",
  "label": "Redband trout",
  "colour": "#a8862c",
  "lines": 6128,
  "polys": 26,
  "polys_merged": 6,
  "vertices": 130872,
  "vertices_ranges": 3787,
  "vertices_merged": 1926,
  "mb": 2.57,
  "parts_dropped_as_degenerate": 5,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "ca_pisces_goose_lake_400",
    "label": "CA, PISCES, Goose Lake",
    "sources": [
     "PISCES 2.0.4 extant range, Oncorhynchus_mykiss_subspecies_SOM11"
    ],
    "runs": [
     "Goose Lake"
    ],
    "state": "CA",
    "notes": [
     "Not a stream. PISCES maps fish onto whole HUC12 watersheds, a median of about 3 km across, so the shape says the fish is somewhere in this watershed, not that it is in any particular channel. Every California species is mapped this way; Oregon and Washington are mapped onto stream arcs instead. The change of shape at the state line is a change of institution, not of fish."
    ],
    "grade": "range",
    "grain": "HUC12 range",
    "lines": 0,
    "polys": 20,
    "polys_merged": 5
   },
   {
    "id": "ca_pisces_mccloud_river_677",
    "label": "CA, PISCES, McCloud River",
    "sources": [
     "PISCES 2.0.4 extant range, Oncorhynchus_mykiss_stonei_SOM10"
    ],
    "runs": [
     "McCloud River"
    ],
    "state": "CA",
    "notes": [
     "Not a stream. PISCES maps fish onto whole HUC12 watersheds, a median of about 3 km across, so the shape says the fish is somewhere in this watershed, not that it is in any particular channel. Every California species is mapped this way; Oregon and Washington are mapped onto stream arcs instead. The change of shape at the state line is a change of institution, not of fish."
    ],
    "grade": "range",
    "grain": "HUC12 range",
    "lines": 0,
    "polys": 6,
    "polys_merged": 1
   },
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_Redband"
    ],
    "runs": [],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 5808,
    "polys": 0,
    "polys_merged": 0
   },
   {
    "id": "wa_swifd_097",
    "label": "WA, SWIFD",
    "sources": [
     "WDFW SWIFD, file geodatabase of 2026-04-17"
    ],
    "runs": [],
    "state": "WA",
    "notes": [
     "These 320 reaches are this project's inference, not a label in the source. SWIFD has no redband category, so redband is read as Rainbow Trout east of the Cascades with a fluvial or adfluvial life history. Redband is understated wherever the source recorded no life history at all."
    ],
    "grade": "inferred",
    "grain": "reach",
    "lines": 320,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "bull_trout",
  "label": "Bull trout",
  "colour": "#2f8fa8",
  "lines": 4063,
  "polys": 0,
  "polys_merged": 0,
  "vertices": 66220,
  "vertices_ranges": 0,
  "vertices_merged": 0,
  "mb": 1.32,
  "parts_dropped_as_degenerate": 0,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_Bulltrout"
    ],
    "runs": [],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 905,
    "polys": 0,
    "polys_merged": 0
   },
   {
    "id": "wa_swifd_097",
    "label": "WA, SWIFD",
    "sources": [
     "WDFW SWIFD, file geodatabase of 2026-04-17"
    ],
    "runs": [],
    "state": "WA",
    "notes": [
     "1,588 of these reaches are presumed rather than recorded: the source marks them as likely habitat, not as a documented observation."
    ],
    "grade": "observed/presumed",
    "grain": "reach",
    "lines": 3158,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "chum",
  "label": "Chum salmon",
  "colour": "#8a4f4f",
  "lines": 2992,
  "polys": 0,
  "polys_merged": 0,
  "vertices": 36265,
  "vertices_ranges": 0,
  "vertices_merged": 0,
  "mb": 0.72,
  "parts_dropped_as_degenerate": 0,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_Chum"
    ],
    "runs": [],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 394,
    "polys": 0,
    "polys_merged": 0
   },
   {
    "id": "wa_swifd_097",
    "label": "WA, SWIFD, Fall + Summer + Winter",
    "sources": [
     "WDFW SWIFD, file geodatabase of 2026-04-17"
    ],
    "runs": [
     "Fall",
     "Summer",
     "Winter"
    ],
    "state": "WA",
    "notes": [
     "564 of these reaches are presumed rather than recorded: the source marks them as likely habitat, not as a documented observation."
    ],
    "grade": "observed/presumed",
    "grain": "reach",
    "lines": 2598,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "pink",
  "label": "Pink salmon",
  "colour": "#d27aa8",
  "lines": 1211,
  "polys": 0,
  "polys_merged": 0,
  "vertices": 12851,
  "vertices_ranges": 0,
  "vertices_merged": 0,
  "mb": 0.26,
  "parts_dropped_as_degenerate": 0,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "wa_swifd_097",
    "label": "WA, SWIFD, Odd Year + Even Year",
    "sources": [
     "WDFW SWIFD, file geodatabase of 2026-04-17"
    ],
    "runs": [
     "Odd Year",
     "Even Year"
    ],
    "state": "WA",
    "notes": [
     "276 of these reaches are presumed rather than recorded: the source marks them as likely habitat, not as a documented observation."
    ],
    "grade": "observed/presumed",
    "grain": "reach",
    "lines": 1211,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "sockeye",
  "label": "Sockeye salmon",
  "colour": "#c23b3b",
  "lines": 1025,
  "polys": 0,
  "polys_merged": 0,
  "vertices": 14915,
  "vertices_ranges": 0,
  "vertices_merged": 0,
  "mb": 0.3,
  "parts_dropped_as_degenerate": 0,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_Sockeye"
    ],
    "runs": [],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 72,
    "polys": 0,
    "polys_merged": 0
   },
   {
    "id": "wa_swifd_097",
    "label": "WA, SWIFD",
    "sources": [
     "WDFW SWIFD, file geodatabase of 2026-04-17"
    ],
    "runs": [],
    "state": "WA",
    "notes": [
     "15 of these reaches are presumed rather than recorded: the source marks them as likely habitat, not as a documented observation."
    ],
    "grade": "observed/presumed",
    "grain": "reach",
    "lines": 953,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "westslope_cutthroat",
  "label": "Westslope cutthroat trout",
  "colour": "#6f8f2f",
  "lines": 900,
  "polys": 0,
  "polys_merged": 0,
  "vertices": 21468,
  "vertices_ranges": 0,
  "vertices_merged": 0,
  "mb": 0.43,
  "parts_dropped_as_degenerate": 0,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_Cutthroat_Westslope"
    ],
    "runs": [],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 10,
    "polys": 0,
    "polys_merged": 0
   },
   {
    "id": "wa_swifd_097",
    "label": "WA, SWIFD",
    "sources": [
     "WDFW SWIFD, file geodatabase of 2026-04-17"
    ],
    "runs": [],
    "state": "WA",
    "notes": [
     "66 of these reaches are presumed rather than recorded: the source marks them as likely habitat, not as a documented observation."
    ],
    "grade": "observed/presumed",
    "grain": "reach",
    "lines": 890,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "mountain_whitefish",
  "label": "Mountain whitefish",
  "colour": "#7d7a70",
  "lines": 795,
  "polys": 53,
  "polys_merged": 2,
  "vertices": 40963,
  "vertices_ranges": 7062,
  "vertices_merged": 1866,
  "mb": 0.71,
  "parts_dropped_as_degenerate": 0,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "ca_pisces_957",
    "label": "CA, PISCES",
    "sources": [
     "PISCES 2.0.4 extant range, Prosopium_williamsoni_SPW01"
    ],
    "runs": [],
    "state": "CA",
    "notes": [
     "Not a stream. PISCES maps fish onto whole HUC12 watersheds, a median of about 3 km across, so the shape says the fish is somewhere in this watershed, not that it is in any particular channel. Every California species is mapped this way; Oregon and Washington are mapped onto stream arcs instead. The change of shape at the state line is a change of institution, not of fish."
    ],
    "grade": "range",
    "grain": "HUC12 range",
    "lines": 0,
    "polys": 53,
    "polys_merged": 2
   },
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_MountainWhitefish"
    ],
    "runs": [],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 368,
    "polys": 0,
    "polys_merged": 0
   },
   {
    "id": "wa_swifd_097",
    "label": "WA, SWIFD",
    "sources": [
     "WDFW SWIFD, file geodatabase of 2026-04-17"
    ],
    "runs": [],
    "state": "WA",
    "notes": [
     "63 of these reaches are presumed rather than recorded: the source marks them as likely habitat, not as a documented observation."
    ],
    "grade": "observed/presumed",
    "grain": "reach",
    "lines": 427,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "bridgelip_sucker",
  "label": "Bridgelip sucker",
  "colour": "#9c6a3a",
  "lines": 305,
  "polys": 0,
  "polys_merged": 0,
  "vertices": 8275,
  "vertices_ranges": 0,
  "vertices_merged": 0,
  "mb": 0.16,
  "parts_dropped_as_degenerate": 0,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_Sucker_Bridgelip"
    ],
    "runs": [],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 305,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "largescale_sucker",
  "label": "Largescale sucker",
  "colour": "#4f6f5f",
  "lines": 270,
  "polys": 0,
  "polys_merged": 0,
  "vertices": 21918,
  "vertices_ranges": 0,
  "vertices_merged": 0,
  "mb": 0.43,
  "parts_dropped_as_degenerate": 0,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_Sucker_Largescale"
    ],
    "runs": [],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 270,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "klamath_largescale_sucker",
  "label": "Klamath largescale sucker",
  "colour": "#b85c2e",
  "lines": 77,
  "polys": 36,
  "polys_merged": 3,
  "vertices": 7843,
  "vertices_ranges": 5062,
  "vertices_merged": 1517,
  "mb": 0.09,
  "parts_dropped_as_degenerate": 1,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "ca_pisces_957",
    "label": "CA, PISCES",
    "sources": [
     "PISCES 2.0.4 extant range, Catostomus_snyderi_CCS01"
    ],
    "runs": [],
    "state": "CA",
    "notes": [
     "Not a stream. PISCES maps fish onto whole HUC12 watersheds, a median of about 3 km across, so the shape says the fish is somewhere in this watershed, not that it is in any particular channel. Every California species is mapped this way; Oregon and Washington are mapped onto stream arcs instead. The change of shape at the state line is a change of institution, not of fish."
    ],
    "grade": "range",
    "grain": "HUC12 range",
    "lines": 0,
    "polys": 36,
    "polys_merged": 3
   },
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_Sucker_KlamathLargescale"
    ],
    "runs": [],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 77,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "lost_river_sucker",
  "label": "Lost River sucker",
  "colour": "#6a4fa0",
  "lines": 47,
  "polys": 27,
  "polys_merged": 2,
  "vertices": 6309,
  "vertices_ranges": 4906,
  "vertices_merged": 1398,
  "mb": 0.06,
  "parts_dropped_as_degenerate": 0,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "ca_pisces_957",
    "label": "CA, PISCES",
    "sources": [
     "PISCES 2.0.4 extant range, Catostomus_luxatus_CCL01"
    ],
    "runs": [],
    "state": "CA",
    "notes": [
     "Not a stream. PISCES maps fish onto whole HUC12 watersheds, a median of about 3 km across, so the shape says the fish is somewhere in this watershed, not that it is in any particular channel. Every California species is mapped this way; Oregon and Washington are mapped onto stream arcs instead. The change of shape at the state line is a change of institution, not of fish."
    ],
    "grade": "range",
    "grain": "HUC12 range",
    "lines": 0,
    "polys": 27,
    "polys_merged": 2
   },
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_Sucker_LostRiver"
    ],
    "runs": [],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 47,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "shortnose_sucker",
  "label": "Shortnose sucker",
  "colour": "#3d9c6a",
  "lines": 40,
  "polys": 44,
  "polys_merged": 2,
  "vertices": 10111,
  "vertices_ranges": 6913,
  "vertices_merged": 1534,
  "mb": 0.09,
  "parts_dropped_as_degenerate": 0,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "ca_pisces_957",
    "label": "CA, PISCES",
    "sources": [
     "PISCES 2.0.4 extant range, Chasmistes_brevirostris_CCB01"
    ],
    "runs": [],
    "state": "CA",
    "notes": [
     "Not a stream. PISCES maps fish onto whole HUC12 watersheds, a median of about 3 km across, so the shape says the fish is somewhere in this watershed, not that it is in any particular channel. Every California species is mapped this way; Oregon and Washington are mapped onto stream arcs instead. The change of shape at the state line is a change of institution, not of fish."
    ],
    "grade": "range",
    "grain": "HUC12 range",
    "lines": 0,
    "polys": 44,
    "polys_merged": 2
   },
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_Sucker_Shortnose"
    ],
    "runs": [],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 40,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "white_sturgeon",
  "label": "White sturgeon",
  "colour": "#5c5c8a",
  "lines": 638,
  "polys": 147,
  "polys_merged": 112,
  "vertices": 32722,
  "vertices_ranges": 28184,
  "vertices_merged": 17656,
  "mb": 0.44,
  "parts_dropped_as_degenerate": 0,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "ca_pisces_957",
    "label": "CA, PISCES",
    "sources": [
     "PISCES 2.0.4 extant range, Acipenser_transmontanus_AAT01"
    ],
    "runs": [],
    "state": "CA",
    "notes": [
     "Not a stream. PISCES maps fish onto whole HUC12 watersheds, a median of about 3 km across, so the shape says the fish is somewhere in this watershed, not that it is in any particular channel. Every California species is mapped this way; Oregon and Washington are mapped onto stream arcs instead. The change of shape at the state line is a change of institution, not of fish."
    ],
    "grade": "range",
    "grain": "HUC12 range",
    "lines": 0,
    "polys": 147,
    "polys_merged": 112
   },
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_SturgeonWhite"
    ],
    "runs": [],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 467,
    "polys": 0,
    "polys_merged": 0
   },
   {
    "id": "wa_swifd_097",
    "label": "WA, SWIFD",
    "sources": [
     "WDFW SWIFD, file geodatabase of 2026-04-17"
    ],
    "runs": [],
    "state": "WA",
    "notes": [
     "34 of these reaches are presumed rather than recorded: the source marks them as likely habitat, not as a documented observation."
    ],
    "grade": "observed/presumed",
    "grain": "reach",
    "lines": 171,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "green_sturgeon",
  "label": "Green sturgeon",
  "colour": "#2e7d4f",
  "lines": 73,
  "polys": 196,
  "polys_merged": 114,
  "vertices": 37527,
  "vertices_ranges": 36334,
  "vertices_merged": 18008,
  "mb": 0.38,
  "parts_dropped_as_degenerate": 0,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "ca_pisces_northern_dps_821",
    "label": "CA, PISCES, Northern DPS",
    "sources": [
     "PISCES 2.0.4 extant range, Acipenser_medirostris_AAM01"
    ],
    "runs": [
     "Northern DPS"
    ],
    "state": "CA",
    "notes": [
     "Not a stream. PISCES maps fish onto whole HUC12 watersheds, a median of about 3 km across, so the shape says the fish is somewhere in this watershed, not that it is in any particular channel. Every California species is mapped this way; Oregon and Washington are mapped onto stream arcs instead. The change of shape at the state line is a change of institution, not of fish."
    ],
    "grade": "range",
    "grain": "HUC12 range",
    "lines": 0,
    "polys": 77,
    "polys_merged": 3
   },
   {
    "id": "ca_pisces_southern_dps_523",
    "label": "CA, PISCES, Southern DPS",
    "sources": [
     "PISCES 2.0.4 extant range, Acipenser_medirostris_AAM02"
    ],
    "runs": [
     "Southern DPS"
    ],
    "state": "CA",
    "notes": [
     "Not a stream. PISCES maps fish onto whole HUC12 watersheds, a median of about 3 km across, so the shape says the fish is somewhere in this watershed, not that it is in any particular channel. Every California species is mapped this way; Oregon and Washington are mapped onto stream arcs instead. The change of shape at the state line is a change of institution, not of fish."
    ],
    "grade": "range",
    "grain": "HUC12 range",
    "lines": 0,
    "polys": 119,
    "polys_merged": 111
   },
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_SturgeonGreen"
    ],
    "runs": [],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 36,
    "polys": 0,
    "polys_merged": 0
   },
   {
    "id": "wa_swifd_097",
    "label": "WA, SWIFD",
    "sources": [
     "WDFW SWIFD, file geodatabase of 2026-04-17"
    ],
    "runs": [],
    "state": "WA",
    "notes": [
     "18 of these reaches are presumed rather than recorded: the source marks them as likely habitat, not as a documented observation."
    ],
    "grade": "presumed",
    "grain": "reach",
    "lines": 37,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "western_river_lamprey",
  "label": "Western river lamprey",
  "colour": "#a0527a",
  "lines": 39,
  "polys": 198,
  "polys_merged": 68,
  "vertices": 34616,
  "vertices_ranges": 34146,
  "vertices_merged": 15631,
  "mb": 0.32,
  "parts_dropped_as_degenerate": 0,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "ca_pisces_957",
    "label": "CA, PISCES",
    "sources": [
     "PISCES 2.0.4 extant range, Lampetra_ayersi_PLA01"
    ],
    "runs": [],
    "state": "CA",
    "notes": [
     "Not a stream. PISCES maps fish onto whole HUC12 watersheds, a median of about 3 km across, so the shape says the fish is somewhere in this watershed, not that it is in any particular channel. Every California species is mapped this way; Oregon and Washington are mapped onto stream arcs instead. The change of shape at the state line is a change of institution, not of fish."
    ],
    "grade": "range",
    "grain": "HUC12 range",
    "lines": 0,
    "polys": 198,
    "polys_merged": 68
   },
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_Lamprey_WesternRiver"
    ],
    "runs": [],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 39,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 },
 {
  "key": "eulachon",
  "label": "Eulachon",
  "colour": "#3a6ea5",
  "lines": 20,
  "polys": 19,
  "polys_merged": 4,
  "vertices": 3435,
  "vertices_ranges": 3159,
  "vertices_merged": 1678,
  "mb": 0.04,
  "parts_dropped_as_degenerate": 0,
  "parts_dropped_off_map": 0,
  "sources": [
   {
    "id": "ca_pisces_957",
    "label": "CA, PISCES",
    "sources": [
     "PISCES 2.0.4 extant range, Thaleichthys_pacificus_OTP01"
    ],
    "runs": [],
    "state": "CA",
    "notes": [
     "Not a stream. PISCES maps fish onto whole HUC12 watersheds, a median of about 3 km across, so the shape says the fish is somewhere in this watershed, not that it is in any particular channel. Every California species is mapped this way; Oregon and Washington are mapped onto stream arcs instead. The change of shape at the state line is a change of institution, not of fish."
    ],
    "grade": "range",
    "grain": "HUC12 range",
    "lines": 0,
    "polys": 19,
    "polys_merged": 4
   },
   {
    "id": "or_odfw_744",
    "label": "OR, ODFW",
    "sources": [
     "ODFW Fish Habitat Distribution 1167_5, fhd_Eulachon"
    ],
    "runs": [],
    "state": "OR",
    "notes": [],
    "grade": "observed",
    "grain": "reach",
    "lines": 20,
    "polys": 0,
    "polys_merged": 0
   }
  ]
 }
];

// Combine a species' per-source geometry into one whole-species view. `only` is a Set of source ids to
// include, or null for all of them. Written by build/make_presence_display.py rather than kept in the
// page, so the rule has one definition (standing rule 44).
function presenceCombined(raw, only) {
  // polys dropped 2026-09-18: the per-watershed rings are no longer written to the data files, so
  // concatenating s.polys here would throw on undefined. Ranges are merged geometry only.
  const out = { lines: [], polys_merged: [] };
  if (!raw || !raw.sources) return out;
  for (const s of raw.sources) {
    if (only && !only.has(s.id)) continue;
    out.lines = out.lines.concat(s.lines);
    out.polys_merged = out.polys_merged.concat(s.polys_merged);
  }
  return out;
}
